name: build

on:
  push:
    branches: master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the image
        run: |
          export tag=${GITHUB_REF##*/}
          if [ "$tag" = "master" ]; then export tag=latest; fi
          docker buildx build \
            --tag xr108/ss-xray:$tag \
            --platform linux/amd64,linux/arm/v7,linux/arm64 --push .
